name: CI

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 6,18 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install deps
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: xmlstarlet
          version: 1.0

      - name: Run script
        env: 
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: bash crawl_news.sh

      - uses: EndBug/add-and-commit@v9 
        with:
          add: './current.txt'
          message: 'gh action: current feed updated'
          default_author: github_actions


